# This is a setup workflow to help test ./install.sh on Mac and linux
# `sudo -E` needs to avoid Permission denied issue
name: test-install-action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
# schedule:
# - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      # Runs a set of commands using the runners shell
      - name: Test for install.sh
        env:
          GO111MODULE: on
        run: |
          export HOMEDIR=$HOME
          export HOMEUSER=$RUNNER_USER
          echo $HOMEDIR
          echo $HOMEUSER
          pwd
          env
          sudo -E ./install.sh
          ls -alt
          ./test/test_install.sh "./test/dependencies_list.txt"
          ./test/test_nuclei_templates.sh ./test/nuclei_templates_list.txt
